// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagement.Data;

#nullable disable

namespace TaskManagement.Migrations
{
    [DbContext(typeof(TaskManagementContext))]
    partial class TaskManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Models.ProjectBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ASSIGNED_BY");

                    b.Property<string>("AssignedUsers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ASSIGNED_USERS");

                    b.Property<string>("Clients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CLIENT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATEDTIME");

                    b.Property<int>("Department")
                        .HasColumnType("integer")
                        .HasColumnName("DEPARTMENT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("END_DATE");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("IsDisabled")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IS_DISABLED");

                    b.Property<int>("Location")
                        .HasColumnType("integer")
                        .HasColumnName("LOCATION");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("PROJECT_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("START_DATE");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("UPDATEDBY");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATEDTIME");

                    b.HasKey("Id");

                    b.ToTable("TB_TASK_PROJECTS", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Models.TaskAcceptanceBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ACCEPTED_DATE");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATEDTIME");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("IsDisabled")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IS_DISABLED");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("TASK_ID");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("UPDATEDBY");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATEDTIME");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("TB_TASK_ACCEPTANCE", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Models.TaskBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ASSIGNED_BY");

                    b.Property<string>("AssignedUsers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ASSIGNED_USERS");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("COMPLETED_DATE");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATEDTIME");

                    b.Property<int>("Department")
                        .HasColumnType("integer")
                        .HasColumnName("DEPARTMENT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DUE_DATE");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("IsDisabled")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IS_DISABLED");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("PROJECT_ID");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TASK_NAME");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("UPDATEDBY");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATEDTIME");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TB_TASKS", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Models.TaskBo", b =>
                {
                    b.HasOne("TaskManagement.Models.ProjectBo", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManagement.Models.ProjectBo", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
